export const actionTypes = {
  FETCH_PLAYER_CARDS: "FETCH_PLAYER_CARDS",
  FETCH_SERVER_CARDS: "FETCH_SERVER_CARDS",
  RESULT_GAME: "RESULT_GAME",
  RESET_PLAYER_CARDS: "RESET_PLAYER_CARDS",
  RESET_SERVER_CARDS: "RESET_SERVER_CARDS",
  RESET_RESULT_GAME: "RESET_RESULT_GAME"
};
